services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Oro\Bundle\AiContentGenerationBundle\Controller\AiContentGenerationController:
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: container.service_subscriber }
